const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const source = path.join(root, 'app/wwwroot/game');
const destination = path.join(root, 'web');
const page = fs.readFileSync(path.join(root, 'app/MainPage.xaml.cs'), 'utf8');
let html = page.slice(page.indexOf('<!DOCTYPE html>'), page.indexOf('</html>') + 7);
html = html.replace('{{css}}', '@import url("game.css");')
  .replace('{{assetScript}}', '')
  .replace(/<script>\s*window\.nativeAds[\s\S]*?<\/script>/, '')
  .replace('<script>\r\n                       {{js}}\r\n                       </script>', '<script src="flight-director.js"></script><script src="game.js"></script>')
  .replace(/<script>\s*\{\{js\}\}\s*<\/script>/, '<script src="flight-director.js"></script><script src="game.js"></script>');
fs.writeFileSync(path.join(destination, 'index.html'), '<!-- Generated by tools/sync-web.cjs from the Android page. -->\n' + html);
for (const file of ['game.js', 'game.css', 'flight-director.js']) fs.copyFileSync(path.join(source, file), path.join(destination, file));
fs.cpSync(path.join(source, 'assets'), path.join(destination, 'assets'), { recursive: true });
console.log('Web preview synchronized with the Android sources.');
